# Generated by Django 2.1 on 2018-08-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_Admin',
            field=models.BooleanField(blank=True),
        ),
    ]
