# Generated by Django 2.1 on 2018-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180827_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_Admin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
